-- anvil 业务表补列中文 COMMENT(供 ruoyi 代码生成器作字段标签;仅加注释,类型不变,幂等)
USE anvil;

-- 项目表
ALTER TABLE projects
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '项目名称',
  MODIFY COLUMN parent_id BIGINT NULL COMMENT '父项目ID',
  MODIFY COLUMN display_name VARCHAR(256) DEFAULT '' COMMENT '项目描述',
  MODIFY COLUMN description TEXT COMMENT '详细描述',
  MODIFY COLUMN user_id INT NULL COMMENT '所有者用户ID(本地users.id)',
  MODIFY COLUMN phase VARCHAR(32) DEFAULT 'concept' COMMENT '设计阶段',
  MODIFY COLUMN path VARCHAR(512) NOT NULL COMMENT '工作区绝对路径',
  MODIFY COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT NULL COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT NULL COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  MODIFY COLUMN del_flag CHAR(1) DEFAULT '0' COMMENT '删除标志（0存在 2删除）';

-- 项目共享授权表
ALTER TABLE shares
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '共享ID',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN owner_id INT NOT NULL COMMENT '授权者用户ID',
  MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
  MODIFY COLUMN target_id INT NOT NULL COMMENT '被授权用户ID',
  MODIFY COLUMN permission VARCHAR(16) DEFAULT 'read' COMMENT '权限(read/comment/edit)',
  MODIFY COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT NULL COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT NULL COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT NULL COMMENT '更新时间',
  MODIFY COLUMN del_flag CHAR(1) DEFAULT '0' COMMENT '删除标志（0存在 2删除）';

-- 对话流水表
ALTER TABLE history_rows
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '流水ID',
  MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
  MODIFY COLUMN seq INT NOT NULL COMMENT '对话行号(项目内)',
  MODIFY COLUMN type VARCHAR(16) NOT NULL COMMENT '消息类型(user/assistant/tool)',
  MODIFY COLUMN timestamp VARCHAR(40) DEFAULT '' COMMENT '消息时间(原始)',
  MODIFY COLUMN data TEXT COMMENT '消息内容JSON',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT NULL COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT NULL COMMENT '创建时间';

-- 设计日志表
ALTER TABLE design_log_rows
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
  MODIFY COLUMN seq INT NOT NULL COMMENT '设计事件序号(项目内)',
  MODIFY COLUMN entry_id VARCHAR(64) DEFAULT '' COMMENT '事件外部ID',
  MODIFY COLUMN action VARCHAR(32) DEFAULT '' COMMENT '动作(model_build/model_clear等)',
  MODIFY COLUMN instruction TEXT COMMENT '用户指令',
  MODIFY COLUMN llm_response TEXT COMMENT 'LLM响应',
  MODIFY COLUMN output_dir VARCHAR(255) DEFAULT '' COMMENT '产物相对目录',
  MODIFY COLUMN result_log TEXT COMMENT '结果日志JSON',
  MODIFY COLUMN q_snapshot TEXT COMMENT 'Q全需求矩阵快照JSON',
  MODIFY COLUMN time VARCHAR(40) DEFAULT '' COMMENT '事件时间(原始)',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT NULL COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT NULL COMMENT '创建时间';

-- dltQ需求账本表
ALTER TABLE dltq_ledger
  MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
  MODIFY COLUMN seq BIGINT NOT NULL DEFAULT 0 COMMENT '加法器递增序号(永不复用)',
  MODIFY COLUMN entries TEXT COMMENT '全需求矩阵JSON',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  MODIFY COLUMN create_by BIGINT NULL COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT NULL COMMENT '创建时间',
  MODIFY COLUMN update_by BIGINT NULL COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT NULL COMMENT '更新时间';

-- 用户映射表(只读管理)
ALTER TABLE users
  COMMENT 'Anvil用户映射表(本地账号↔ruoyi sys_user,只读)',
  MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '本地用户ID',
  MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录账号',
  MODIFY COLUMN password_hash VARCHAR(256) NOT NULL COMMENT '口令占位(恒!,凭据在ruoyi)',
  MODIFY COLUMN sys_user_id BIGINT NULL COMMENT 'ruoyi sys_user.user_id',
  MODIFY COLUMN tenant_id VARCHAR(20) DEFAULT '000000' COMMENT '租户编号',
  MODIFY COLUMN display_name VARCHAR(128) DEFAULT '' COMMENT '昵称',
  MODIFY COLUMN role VARCHAR(32) DEFAULT 'viewer' COMMENT '角色(admin/engineer/viewer)',
  MODIFY COLUMN status VARCHAR(16) DEFAULT 'active' COMMENT '状态(active/disabled)',
  MODIFY COLUMN is_test TINYINT(1) DEFAULT 0 COMMENT '是否测试用户',
  ADD COLUMN create_dept BIGINT NULL COMMENT '创建部门',
  ADD COLUMN create_by BIGINT NULL COMMENT '创建者',
  ADD COLUMN create_time DATETIME NULL COMMENT '创建时间',
  ADD COLUMN update_by BIGINT NULL COMMENT '更新者',
  ADD COLUMN update_time DATETIME NULL COMMENT '更新时间';

-- 追加日志表补 update 审计列(可空,恒 NULL;为兼容 ruoyi TenantEntity 基类映射)
ALTER TABLE history_rows
  ADD COLUMN update_by BIGINT NULL COMMENT '更新者' AFTER create_by,
  ADD COLUMN update_time DATETIME NULL COMMENT '更新时间' AFTER create_time;
ALTER TABLE design_log_rows
  ADD COLUMN update_by BIGINT NULL COMMENT '更新者' AFTER create_by,
  ADD COLUMN update_time DATETIME NULL COMMENT '更新时间' AFTER create_time;
